services:
  - type: web
    name: backend-service
    env: docker
    build:
      dockerfilePath: ./backend/Dockerfile
      contextPath: ./backend/
    ports:
      - port: 8000
        externalPort: 8000
        host: 127.0.0.1

  - type: web
    name: frontend-service
    env: docker
    build:
      dockerfilePath: ./frontend/Dockerfile
      contextPath: ./frontend/
    ports:
      - port: 3000
        externalPort: 3000
        host: 127.0.0.1
